# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYAu5sZuA5bqoeQOK_DVltDNoN4dMu9t
"""

pip install streamlit selenium webdriver-manager pandas

import streamlit as st
import pandas as pd
import time

# 1. Dizajni i Faqes Web
st.set_page_config(page_title="Competitor AI Scanner", layout="wide")
st.title("📊 Competitor AI Scanner")
st.subheader("Analiza e Vodafone, T-Mobile & Orange")

# 2. Krijojmë disa të dhëna "shembull" (që do vijnë nga scraping)
# Në një projekt real, këtu do vendosnim kodin e Selenium
data = {
    "Kompania": ["Vodafone", "T-Mobile", "Orange"],
    "Oferta Kryesore": ["Unlimited L", "Magenta Gold", "Go Fly"],
    "Çmimi (€)": [25, 22, 20],
    "GB": ["Pa limit", "50 GB", "100 GB"],
    "Sentiment i Klientit": ["Pozitiv", "Neutral", "Negativ"]
}

df = pd.DataFrame(data)

# 3. Shfaqja në Faqe
col1, col2 = st.columns([2, 1])

with col1:
    st.write("### Ofertat e Fundit")
    st.table(df)

with col2:
    st.write("### AI Insights")
    st.info("AI: T-Mobile ka çmimin më konkurrues për momentin.")
    if st.button("Rifresko të dhënat"):
        st.warning("Roboti po skanon faqet... Prit pak.")
        # Këtu roboti do bënte punën e tij realisht
        streamlit run app.py
