# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYAu5sZuA5bqoeQOK_DVltDNoN4dMu9t
"""

import streamlit as st
import pandas as pd
import time

# 1. Dizajni i Faqes Web
st.set_page_config(page_title="Competitor AI Scanner", layout="wide")
st.title("📊 Competitor AI Scanner")
st.subheader("Analiza e Vodafone, One & E-Sim")

# 2. Krijojmë disa të dhëna "shembull" (që do vijnë nga scraping)
# Në një projekt real, këtu do vendosnim kodin e Selenium
data = {
    "Kompania": ["Vodafone", "One", "E-Sim"],
    "Oferta Kryesore": ["Unlimited 5G", "The one for you", "Everywere you go"],
    "Çmimi (€)": [25, 10, 10],
    "GB": ["Pa limit", "20 GB", "5 GB"],
    "Sentiment i Klientit": ["Pozitiv", "Neutral", "Negativ"]
}

df = pd.DataFrame(data)

# 3. Shfaqja në Faqe
col1, col2 = st.columns([2, 1])

with col1:
    st.write("### Ofertat e Fundit")
    st.table(df)

with col2:
    st.write("### AI Insights")
    st.info("AI: One ka çmimin më konkurrues për momentin.")
    if st.button("Rifresko të dhënat"):
        st.warning("Roboti po skanon faqet... Prit pak.")
        # Këtu roboti do bënte punën e tij realisht
       
